[package]
name = "radial_menu_overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi"]}
winit = "0.27"
ash = { version = "0.35.2" }